version: '3'

vars:
  BINARY: godocs-inbox

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the binary
    cmds:
      - go build -o {{.BINARY}} .

  run:
    desc: Build and run
    deps: [build]
    cmds:
      - ./{{.BINARY}}

  run:demo:
    desc: Build and run in demo mode
    deps: [build]
    cmds:
      - ./{{.BINARY}} -demo

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  test:
    desc: Run tests
    cmds:
      - go test ./...

  check:
    desc: Run fmt, vet, and test
    cmds:
      - task: fmt
      - task: vet
      - task: test

  deps:tidy:
    desc: Tidy module dependencies
    cmds:
      - go mod tidy

  release:
    desc: "Commit, tag, and release — task release VERSION=v0.4.0 COMMENT='Add feature X'"
    deps: [check]
    requires:
      vars: [VERSION, COMMENT]
    cmds:
      - git add -A
      - git diff --cached --quiet || git commit -m "{{.COMMENT}}"
      - git tag -a {{.VERSION}} -m "{{.COMMENT}}"
      - git push origin main {{.VERSION}}
      - goreleaser release --clean

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -f {{.BINARY}}
      - rm -rf demo-inbox demo-tagged
